/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jamed
 */
public class GUIListarPeriferico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIListarPeriferico.class.getName());

    /**
     * Creates new form GUIListarPeriferico
     */
    public GUIListarPeriferico() {
        initComponents();
        this.setResizable(false);
        this.pack(); 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListaPeriferico = new javax.swing.JTable();
        btnListarPeriferico = new javax.swing.JButton();
        btnSumatoriaPeriferico = new javax.swing.JButton();
        lblTotal2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jListaPeriferico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Marca", "Precio", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jListaPeriferico);

        btnListarPeriferico.setText("Listar");
        btnListarPeriferico.addActionListener(this::btnListarPerifericoActionPerformed);

        btnSumatoriaPeriferico.setText("Sumatoria");
        btnSumatoriaPeriferico.addActionListener(this::btnSumatoriaPerifericoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnListarPeriferico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSumatoriaPeriferico)))
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotal2, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarPeriferico)
                    .addComponent(btnSumatoriaPeriferico))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarPerifericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPerifericoActionPerformed
        
    try {
            String[] columnas = {"ID Periférico", "Nombre", "Precio", "Es Gamer"};
            DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
            
            com.mongodb.client.MongoDatabase db = conexion.DatabaseConecction.getDatabase();
            
            for (org.bson.Document doc : db.getCollection("Perifericos").find(com.mongodb.client.model.Filters.eq("estado", "A"))) {
                Object[] fila = new Object[4];
                fila[0] = doc.getInteger("id");
                fila[1] = doc.getString("nombre");
                fila[2] = doc.getDouble("precio");
                fila[3] = doc.getBoolean("es_gamer") ? "Sí" : "No";
                
                modelo.addRow(fila);
            }
            
            jListaPeriferico.setModel(modelo);
            
        } catch (Exception e) {
            System.err.println("Error al listar periféricos: " + e.getMessage());
        }
    }//GEN-LAST:event_btnListarPerifericoActionPerformed

    private void btnSumatoriaPerifericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumatoriaPerifericoActionPerformed
       try {
            com.mongodb.client.MongoDatabase db = conexion.DatabaseConecction.getDatabase();
            double total = 0;
            
            for (org.bson.Document doc : db.getCollection("Perifericos").find(com.mongodb.client.model.Filters.eq("estado", "A"))) {
                total += doc.getDouble("precio");
            }
            
            lblTotal2.setText("Total Periféricos: $" + total);
            
        } catch (Exception e) {
            System.err.println("Error en sumatoria periféricos: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSumatoriaPerifericoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIListarPeriferico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarPeriferico;
    private javax.swing.JButton btnSumatoriaPeriferico;
    private javax.swing.JTable jListaPeriferico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal2;
    // End of variables declaration//GEN-END:variables
}
