/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import javax.swing.JOptionPane;


/**
 *
 * @author jamed
 */
public class GUIListarPc extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIListarPc.class.getName());

    /**
     * Creates new form GUIListarPc
     */
    public GUIListarPc() {
        initComponents();
        this.setResizable(false);
        this.pack(); 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListaPc = new javax.swing.JTable();
        btnListarPc = new javax.swing.JButton();
        btnSumatoria = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jListaPc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Marca", "Precio", "Cliente", "Periferico"
            }
        ));
        jScrollPane1.setViewportView(jListaPc);

        btnListarPc.setText("Listar");
        btnListarPc.addActionListener(this::btnListarPcActionPerformed);

        btnSumatoria.setText("Sumatoria Precios");
        btnSumatoria.addActionListener(this::btnSumatoriaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(758, 758, 758))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnListarPc)
                        .addGap(242, 242, 242)
                        .addComponent(btnSumatoria))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSumatoria)
                    .addComponent(btnListarPc))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPcActionPerformed
       try {
            String[] columnas = {"ID PC", "Marca", "Precio PC", "Cliente Asignado", "Periférico Incluido"};
            javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0);
            
            java.util.List<org.bson.Document> pcs = Servicio.ServicioPC.listarPcs();
            
            for (org.bson.Document doc : pcs) {
                Object[] fila = new Object[5];
                fila[0] = doc.getInteger("id");
                fila[1] = doc.getString("marca");
                fila[2] = doc.getDouble("precio");
                
                fila[3] = doc.containsKey("nombre_cliente") ? doc.getString("nombre_cliente") : "Sin cliente";
                fila[4] = doc.containsKey("nombre_periferico") ? doc.getString("nombre_periferico") : "Sin periférico";
                
                modelo.addRow(fila);
            }
            
            jListaPc.setModel(modelo);
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al listar en la grilla de PCs: " + e.getMessage());
        }
    }//GEN-LAST:event_btnListarPcActionPerformed

    private void btnSumatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumatoriaActionPerformed
        try {
            com.mongodb.client.MongoDatabase db = conexion.DatabaseConecction.getDatabase();
            double total = 0;
            
            for (org.bson.Document doc : db.getCollection("PCs").find(com.mongodb.client.model.Filters.eq("estado", "A"))) {
                total += doc.getDouble("precio");
            }
            
            lblTotal.setText("Total Inventario PCs: $" + total);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al calcular sumatoria: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSumatoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIListarPc().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarPc;
    private javax.swing.JButton btnSumatoria;
    private javax.swing.JTable jListaPc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
}
