/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author jamed
 */
public class GUIPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIPrincipal.class.getName());

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        System.out.println("El constructor de GUIPrincipal se está ejecutando...");
        initComponents();
        this.setResizable(false);
        this.pack(); 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        lblImagen = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jArchivo = new javax.swing.JMenu();
        jPcs = new javax.swing.JMenu();
        jAdicionarPc = new javax.swing.JMenuItem();
        jListarPc = new javax.swing.JMenuItem();
        jBuscarPc = new javax.swing.JMenuItem();
        jActualizarPc = new javax.swing.JMenuItem();
        jEliminarPc = new javax.swing.JMenuItem();
        jClientes = new javax.swing.JMenu();
        jAdicionarCliente = new javax.swing.JMenuItem();
        jListarClientes = new javax.swing.JMenuItem();
        jBuscarCliente = new javax.swing.JMenuItem();
        jActualizarCliente = new javax.swing.JMenuItem();
        jEliminarCliente = new javax.swing.JMenuItem();
        jPerifericos = new javax.swing.JMenu();
        jAdicionarPeriferico = new javax.swing.JMenuItem();
        jListarPeriferico = new javax.swing.JMenuItem();
        jBuscarPeriferico = new javax.swing.JMenuItem();
        jActualizarPeriferico = new javax.swing.JMenuItem();
        jEliminarPeriferico = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblImagen.setText("PROTOTIPO 2");

        jArchivo.setText("Archivo");
        jMenuBar2.add(jArchivo);

        jPcs.setText("PCs");

        jAdicionarPc.setText("Adicionar");
        jAdicionarPc.addActionListener(this::jAdicionarPcActionPerformed);
        jPcs.add(jAdicionarPc);

        jListarPc.setText("Listar");
        jListarPc.addActionListener(this::jListarPcActionPerformed);
        jPcs.add(jListarPc);

        jBuscarPc.setText("Buscar");
        jBuscarPc.addActionListener(this::jBuscarPcActionPerformed);
        jPcs.add(jBuscarPc);

        jActualizarPc.setText("Actualizar");
        jActualizarPc.addActionListener(this::jActualizarPcActionPerformed);
        jPcs.add(jActualizarPc);

        jEliminarPc.setText("Eiminar");
        jEliminarPc.addActionListener(this::jEliminarPcActionPerformed);
        jPcs.add(jEliminarPc);

        jMenuBar2.add(jPcs);

        jClientes.setText("Clientes");

        jAdicionarCliente.setText("Adicionar");
        jAdicionarCliente.addActionListener(this::jAdicionarClienteActionPerformed);
        jClientes.add(jAdicionarCliente);

        jListarClientes.setText("Listar");
        jListarClientes.addActionListener(this::jListarClientesActionPerformed);
        jClientes.add(jListarClientes);

        jBuscarCliente.setText("Buscar");
        jBuscarCliente.addActionListener(this::jBuscarClienteActionPerformed);
        jClientes.add(jBuscarCliente);

        jActualizarCliente.setText("Actualizar");
        jActualizarCliente.addActionListener(this::jActualizarClienteActionPerformed);
        jClientes.add(jActualizarCliente);

        jEliminarCliente.setText("Eliminar");
        jEliminarCliente.addActionListener(this::jEliminarClienteActionPerformed);
        jClientes.add(jEliminarCliente);

        jMenuBar2.add(jClientes);

        jPerifericos.setText("Perifericos");

        jAdicionarPeriferico.setText("Adicionar");
        jAdicionarPeriferico.addActionListener(this::jAdicionarPerifericoActionPerformed);
        jPerifericos.add(jAdicionarPeriferico);

        jListarPeriferico.setText("Listar");
        jListarPeriferico.addActionListener(this::jListarPerifericoActionPerformed);
        jPerifericos.add(jListarPeriferico);

        jBuscarPeriferico.setText("Buscar");
        jBuscarPeriferico.addActionListener(this::jBuscarPerifericoActionPerformed);
        jPerifericos.add(jBuscarPeriferico);

        jActualizarPeriferico.setText("Actualizar");
        jActualizarPeriferico.addActionListener(this::jActualizarPerifericoActionPerformed);
        jPerifericos.add(jActualizarPeriferico);

        jEliminarPeriferico.setText("Eliminar");
        jEliminarPeriferico.addActionListener(this::jEliminarPerifericoActionPerformed);
        jPerifericos.add(jEliminarPeriferico);

        jMenuBar2.add(jPerifericos);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(lblImagen)
                .addContainerGap(1745, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(lblImagen)
                .addContainerGap(1880, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAdicionarPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdicionarPcActionPerformed
        GUIAdicionarPc ventanaAdicionar = new GUIAdicionarPc ();
        ventanaAdicionar.setVisible(true);
    }//GEN-LAST:event_jAdicionarPcActionPerformed

    private void jListarPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListarPcActionPerformed
        GUIListarPc ventanaListar = new GUIListarPc ();
        ventanaListar.setVisible(true);
    }//GEN-LAST:event_jListarPcActionPerformed

    private void jBuscarPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarPcActionPerformed
        GUIBuscarPc ventanaBuscar = new GUIBuscarPc ();
        ventanaBuscar.setVisible(true);
    }//GEN-LAST:event_jBuscarPcActionPerformed

    private void jActualizarPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActualizarPcActionPerformed
        GUIActualizarPc ventanaActualizar = new GUIActualizarPc ();
        ventanaActualizar.setVisible(true);
    }//GEN-LAST:event_jActualizarPcActionPerformed

    private void jEliminarPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarPcActionPerformed
        GUIEliminarPc ventanaEliminar = new GUIEliminarPc ();
        ventanaEliminar.setVisible(true);
    }//GEN-LAST:event_jEliminarPcActionPerformed

    private void jAdicionarPerifericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdicionarPerifericoActionPerformed
        GUIAdicionarPeriferico ventanaAdicionar = new GUIAdicionarPeriferico ();
        ventanaAdicionar.setVisible(true);
    }//GEN-LAST:event_jAdicionarPerifericoActionPerformed

    private void jListarPerifericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListarPerifericoActionPerformed
        GUIListarPeriferico ventanaListar = new GUIListarPeriferico ();
        ventanaListar.setVisible(true);
    }//GEN-LAST:event_jListarPerifericoActionPerformed

    private void jBuscarPerifericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarPerifericoActionPerformed
        GUIBuscarPeriferico ventanaBuscar = new GUIBuscarPeriferico ();
        ventanaBuscar.setVisible(true);
    }//GEN-LAST:event_jBuscarPerifericoActionPerformed

    private void jActualizarPerifericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActualizarPerifericoActionPerformed
        GUIActualizarPeriferico ventanaActualizar = new GUIActualizarPeriferico ();
        ventanaActualizar.setVisible(true);
    }//GEN-LAST:event_jActualizarPerifericoActionPerformed

    private void jEliminarPerifericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarPerifericoActionPerformed
        GUIEliminarPeriferico ventanaEliminar = new GUIEliminarPeriferico ();
        ventanaEliminar.setVisible(true);
    }//GEN-LAST:event_jEliminarPerifericoActionPerformed

    private void jAdicionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdicionarClienteActionPerformed
        GUIAdicionarCliente ventanaAdicionar = new GUIAdicionarCliente ();
        ventanaAdicionar.setVisible(true);
    }//GEN-LAST:event_jAdicionarClienteActionPerformed

    private void jListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListarClientesActionPerformed
        GUIListarCliente ventanaListar = new GUIListarCliente ();
        ventanaListar.setVisible(true);
    }//GEN-LAST:event_jListarClientesActionPerformed

    private void jBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarClienteActionPerformed
        GUIBuscarCliente ventanaBuscar = new GUIBuscarCliente ();
        ventanaBuscar.setVisible(true);
    }//GEN-LAST:event_jBuscarClienteActionPerformed

    private void jActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActualizarClienteActionPerformed
        GUIActualizarCliente ventanaActualizar = new GUIActualizarCliente ();
        ventanaActualizar.setVisible(true);
    }//GEN-LAST:event_jActualizarClienteActionPerformed

    private void jEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarClienteActionPerformed
        GUIEliminarCliente ventanaEliminar = new GUIEliminarCliente ();
        ventanaEliminar.setVisible(true);
    }//GEN-LAST:event_jEliminarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIPrincipal().setVisible(true));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jActualizarCliente;
    private javax.swing.JMenuItem jActualizarPc;
    private javax.swing.JMenuItem jActualizarPeriferico;
    private javax.swing.JMenuItem jAdicionarCliente;
    private javax.swing.JMenuItem jAdicionarPc;
    private javax.swing.JMenuItem jAdicionarPeriferico;
    private javax.swing.JMenu jArchivo;
    private javax.swing.JMenuItem jBuscarCliente;
    private javax.swing.JMenuItem jBuscarPc;
    private javax.swing.JMenuItem jBuscarPeriferico;
    private javax.swing.JMenu jClientes;
    private javax.swing.JMenuItem jEliminarCliente;
    private javax.swing.JMenuItem jEliminarPc;
    private javax.swing.JMenuItem jEliminarPeriferico;
    private javax.swing.JMenuItem jListarClientes;
    private javax.swing.JMenuItem jListarPc;
    private javax.swing.JMenuItem jListarPeriferico;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jPcs;
    private javax.swing.JMenu jPerifericos;
    private javax.swing.JLabel lblImagen;
    // End of variables declaration//GEN-END:variables
}
